services:
  mongodb:
    image: mongo:latest
    container_name: py_backend_mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - ./mongo-data:/data/db

# volumes:
#   mongo-data:

# The URI to connect to MongoDB is: mongodb://root:examplepassword@localhost:27017/
